### ISSUE TITLE
unable to open animation window in editor

### ISSUE THREAD

**Issue by AMPW-german** [ps-hek/Liftoff.MovingObjects#1]
Hi, 
first of all, very nice mod you made, I'm absolutly enjoing the existing maps.
After seeing this I got a few map ideas but after upgrading from 1.0.6 to 1.0.8 I'm now completly unable to add animations in the editor. 
The type window on the right side is visible, but I'm unable to click on it, it just deselects the selected block. With 1.0.6 it was possible to add animations, but only barely readable.
I'm on windows 11 only with this mod installed. For the upgrade I extraced all the files from the archive in the liftoff folder and overwritten all but I haven't deleted anything.
If you need any further information (idk if log files are a thing here too) I'm happy to help.

Looking forward to hear from you and have a nice day,
AMPW

**Comment by ps-hek** [comment]
Hello. Please try https://github.com/ps-hek/Liftoff.MovingObjects/releases/tag/1.0.9
If it does not help, if possible send a short where you can see this bug.

**Comment by AMPW-german** [comment]
Hi, so I did some further testing with the new version and (disclaimer, I haven't tested all maps) only on Surtur and Permafrost does the animation window not work, all other maps seem fine. The old version was probaply also fine.  Guess I'm gonna use on of the other maps for now. 
I don't really know why the new maps are different there but at least I can now use it.

**Comment by ps-hek** [comment]
Thanks for the map detail, that will make it easier to investigate

**Comment by ps-hek** [comment]
Fixed https://github.com/ps-hek/Liftoff.MovingObjects/releases/tag/1.0.12
